install via list

diff --git a/bin/nodenv-default-packages b/bin/nodenv-default-packages
--- a/bin/nodenv-default-packages
+++ b/bin/nodenv-default-packages
@@ -57,34 +57,14 @@ list_default_packages() {
 }
 
 install_default_packages() {
-  [ -r "${NODENV_ROOT}/default-packages" ] || return 0
+  local package
 
-  local line package_name package_version package_spec
-
-  # Read package names and versions from $NODENV_ROOT/default-packages.
-  while IFS=" " read -ra line; do
-
-    # Skip empty lines.
-    [ "${#line[@]}" -gt 0 ] || continue
-
-    # Skip comment lines that begin with `#`.
-    [ "${line[0]:0:1}" != "#" ] || continue
-
-    package_name="${line[0]}"
-    package_version="${line[*]:1}"
-
-    if [ -n "$package_version" ]; then
-      package_spec="${package_name}@${package_version}"
-    else
-      package_spec="$package_name"
-    fi
-
+  list_default_packages | while read -r package; do
     # Invoke `npm install -g` in the just-installed Node.
-    NODENV_VERSION="$VERSION_NAME" nodenv-exec npm install -g "$package_spec" || {
-    echo "nodenv: error installing package \`$package_name'"
-  } >&2
-
-done < "${NODENV_ROOT}/default-packages"
+    NODENV_VERSION="$VERSION_NAME" nodenv-exec npm install -g "$package" || {
+      echo "nodenv: error installing package \`$package'"
+    } >&2
+  done
 }
 
 unset cmd
